### PR TITLE
Add get() overload for built-in arrays

### PR DESCRIPTION
**Pull request by ricky65**
Hi,

I added an overload of get() for built-in arrays. I know this isn’t completely necessary as we can already write get(std::begin(carray), std::end(carray) ) though I prefer less verbosity.

I deliberated between returning a pointer or a reference. I decided to return a pointer for consistency with the other overloads; if we passed a built-in array as above it would return an iterator, and the container overload also returns an iterator. 

I’d be grateful for your feedback.

If you like I’d be happy to write tests and update the documentation.

Kind regards,

Riccardo

### CODE REVIEW

**Comment by effolkronium** [comment]
Hi Riccardo,

Thanks for your commit, it's looks very nice. 

Since the main purpose of this library is convenient usage, this feature is really important.

I have not enough time on next few days, so if you can, it would be great to add test case and update doc. But if you can't, i'll do this later next week, with merging into the master branch.

**Comment by ricky65** [comment]
Thanks for your feedback.

Today I will start on adding the test case and updating the doc.

**Comment by ricky65** [comment]
I have added a test case (I used the iterator range/container test cases as a template). I've also updated README.md with an example.  Let me know if I've missed something.

**Comment by effolkronium** [comment]
Good job 👍

**Comment by ricky65** [comment]
Thanks, and thank you for creating this great little library. I want it in the Standard one day!

**Pull request merged**
